### ISSUE TITLE
Capstone Project Module 2

### ISSUE THREAD

**Issue by oovillagran** [oovillagran/Capstone-Module2#21]
https://github.com/oovillagran/Capstone-Module2/projects/1

There are two people in our team:

- @naanmohammed 
- @oovillagran

**Comment by thecodechaser** [comment]
## STATUS: CHANGES REQUIRED ♻️ 

## Hi @oovillagran, and @naanmohammed👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Required Changes ♻️

- [ ] Please make sure to assign team members to all group task cards as you did for other task cards. ( You can divide the group tasks among team members or you can assign all team members to group tasks).

![image](https://user-images.githubusercontent.com/83803414/234115890-8518be10-4511-44f7-9fb7-e77daa2107a5.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by oovillagran** [comment]
Hello @thecodechaser,

Thank you for your kind review. We already assign all the activities as required.👍

**Comment by KanzaTahreem** [comment]
# Approved 🥳

Hi @oovillagran & @naanmohammed 👋

Great work implementing the suggested changes. 💪

**_Your project is COMPLETE! You can go ahead and start working on your capstone project! 🚀 Congratulations!_**

## Highlights 🎯
There are some excellent points that you have made perfectly. Keep up the great work! 👏

-  ✅ All cards are assigned to team members
-  ✅ Cards are assigned in a fair way 
-  ✅ Cards with `group task` are assigned 

## Optional suggestions ❕
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
